apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-sentinel.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.secrets.databaseUrl }}"
  REDIS_URL: "{{ .Values.secrets.redisUrl }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.secrets.kafkaBootstrapServers }}"
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  API_KEY: "{{ .Values.secrets.apiKey }}"
  ENCRYPTION_KEY: "{{ .Values.secrets.encryptionKey }}"
  ARCHIVE_BUCKET: "{{ .Values.externalServices.s3Bucket }}"
  CLICKHOUSE_URL: "{{ .Values.externalServices.clickhouseUrl }}"
