apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-sentinel.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
  REDIS_URL: "{{ .Values.externalServices.redisUrl }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.externalServices.kafkaBootstrap }}"
  ARCHIVE_BUCKET: "{{ .Values.externalServices.s3Bucket }}"
  CLICKHOUSE_URL: "{{ .Values.externalServices.clickhouseUrl }}"
