"""Initial baseline

Revision ID: 40592094d3d4
Revises: 
Create Date: 2026-03-09 09:43:21.756751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40592094d3d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_collections_account_id'), 'api_collections', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_account_id'), 'api_endpoints', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_collection_id'), 'api_endpoints', ['collection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_malicious_event_records_account_id'), 'malicious_event_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_malicious_event_records_api_collection_id'), 'malicious_event_records', ['api_collection_id'], unique=False)
    op.create_index(op.f('ix_malicious_event_records_filter_id'), 'malicious_event_records', ['filter_id'], unique=False)
    op.create_index(op.f('ix_test_accounts_account_id'), 'test_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_test_runs_account_id'), 'test_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_account_id'), 'vulnerabilities', ['account_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_endpoint_id'), 'vulnerabilities', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_template_id'), 'vulnerabilities', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_template_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_endpoint_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_account_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_index(op.f('ix_test_runs_account_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_accounts_account_id'), table_name='test_accounts')
    op.drop_index(op.f('ix_malicious_event_records_filter_id'), table_name='malicious_event_records')
    op.drop_index(op.f('ix_malicious_event_records_api_collection_id'), table_name='malicious_event_records')
    op.drop_index(op.f('ix_malicious_event_records_account_id'), table_name='malicious_event_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_api_endpoints_collection_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_account_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_collections_account_id'), table_name='api_collections')
    # ### end Alembic commands ###
