"""Add missing account_id columns

Revision ID: bc36458285db
Revises: 40592094d3d4
Create Date: 2026-03-09 09:44:10.260709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc36458285db'
down_revision: Union[str, None] = '40592094d3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malicious_events', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_malicious_events_account_id'), 'malicious_events', ['account_id'], unique=False)
    op.add_column('request_logs', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_request_logs_account_id'), 'request_logs', ['account_id'], unique=False)
    op.add_column('sample_data', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_sample_data_account_id'), 'sample_data', ['account_id'], unique=False)
    op.add_column('test_schedules', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_test_schedules_account_id'), 'test_schedules', ['account_id'], unique=False)
    op.add_column('threat_actors', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_threat_actors_account_id'), 'threat_actors', ['account_id'], unique=False)
    op.add_column('waf_events', sa.Column('account_id', sa.BigInteger(), nullable=False, server_default="1000000"))
    op.create_index(op.f('ix_waf_events_account_id'), 'waf_events', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waf_events_account_id'), table_name='waf_events')
    op.drop_column('waf_events', 'account_id')
    op.drop_index(op.f('ix_threat_actors_account_id'), table_name='threat_actors')
    op.drop_column('threat_actors', 'account_id')
    op.drop_index(op.f('ix_test_schedules_account_id'), table_name='test_schedules')
    op.drop_column('test_schedules', 'account_id')
    op.drop_index(op.f('ix_sample_data_account_id'), table_name='sample_data')
    op.drop_column('sample_data', 'account_id')
    op.drop_index(op.f('ix_request_logs_account_id'), table_name='request_logs')
    op.drop_column('request_logs', 'account_id')
    op.drop_index(op.f('ix_malicious_events_account_id'), table_name='malicious_events')
    op.drop_column('malicious_events', 'account_id')
    # ### end Alembic commands ###
